/** Shared class names for admin islands (Darkroom tokens in `global.css`). */

export const adminClass = {
  fg: 'admin-fg',
  fgMuted: 'admin-fg-muted',
  accent: 'admin-accent',
  link: 'admin-link',
  linkMuted: 'admin-link-muted',
  field: 'admin-field',
  fieldSm: 'admin-field admin-field--sm',
  btnPrimary: 'admin-btn-primary',
  panel: 'admin-panel',
  panelDashed: 'admin-panel admin-panel--dashed',
  uploadSection: 'admin-panel admin-upload-section',
  toolbar: 'admin-toolbar',
  status: 'admin-status',
  tableWrap: 'admin-table-wrap',
  table: 'admin-table',
  tableHeadRow: 'admin-table__head-row',
  tableRow: 'admin-table__row',
  tableTh: 'admin-table__th',
  sectionHeading: 'admin-section-heading',
  thumb: 'admin-thumb',
  code: 'admin-code',
  footnote: 'admin-footnote',
  progress: 'admin-progress',
} as const;
